/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.ocelotds.processors;

import org.ocelotds.annotations.DataService;
import java.io.IOException;
import java.io.Writer;
import java.util.Random;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementVisitor;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

/**
 * Processor of annotation org.ocelotds.annotations.DataService
 *
 * @author hhfrancois
 */
@SupportedAnnotationTypes(value = {OcelotProcessor.DATASERVICE_AT})
@SupportedSourceVersion(SourceVersion.RELEASE_7)
public class OcelotProcessor extends AbstractProcessor {

	public final static String DATASERVICE_AT = "org.ocelotds.annotations.DataService";
	private final static Random RANDOM = new Random();
	private static boolean done = false;

	static boolean isDone() {
		return done;
	}

	static void setDone(boolean done) {
		OcelotProcessor.done = done;
	}

	/**
	 * Tools for access filesystem
	 */
	private Filer filer;

	/**
	 * Tools for log processor
	 */
	private Messager messager;

	/**
	 * Init processor<br>
	 * get filer, messager<br>
	 * get options
	 *
	 */
	@Override
	public void init(ProcessingEnvironment processingEnv) {
		super.init(processingEnv);
		messager = processingEnv.getMessager();
		filer = processingEnv.getFiler();
	}

	@Override
	public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
		// check if process was done on previous round
		if (OcelotProcessor.isDone() || roundEnv.processingOver()) { // Returns true if types generated by this round will not be subject to a subsequent round of annotation processing; returns false otherwise.
			return true; //if is it : stop
		}
		// Create provider of ocelot-services.js
		String js = createJSServicesProvider();
		// Create provider of json
		String json = createJsonServicesProvider();

		try {
			// Create file ocelot-services.js      
			try (Writer writer = getOpendResourceFileObjectWriter(js, ProviderType.JAVASCRIPT)) {
				ElementVisitor visitor = new DataServiceVisitorJsBuilder(processingEnv);
				for (Element element : roundEnv.getElementsAnnotatedWith(DataService.class)) {
					messager.printMessage(Diagnostic.Kind.MANDATORY_WARNING, " javascript generation class : " + element);
					element.accept(visitor, writer);
				}
			}
			// Create json services file       
			try (Writer writer = getOpendResourceFileObjectWriter(json, ProviderType.JSON)) {
				boolean first = true;
				for (Element element : roundEnv.getElementsAnnotatedWith(DataService.class)) {
					messager.printMessage(Diagnostic.Kind.MANDATORY_WARNING, " json generation class : " + element);
					element.accept(new DataServiceVisitorJsonBuilder(processingEnv, first), writer);
					first = false;
				}
			}
		} catch (IOException e) {
			messager.printMessage(Diagnostic.Kind.ERROR, e.getMessage());
		}
		OcelotProcessor.setDone(true);
		return true;
	}

	/**
	 * Create provider of ocelot-services.js and return a part of unic name for ocelot-service.js
	 *
	 * @return
	 */
	String createJSServicesProvider() {
		// Creation du provider de ocelot-services.js
		String prefix = "srv_" + RANDOM.nextInt(100_000_000);
		createServicesProvider(prefix, ProviderType.JAVASCRIPT);
		return prefix;
	}

	/**
	 * Create provider of ocelot-services.js and return a part of unic name for ocelot-service.js
	 *
	 * @return
	 */
	String createJsonServicesProvider() {
		// Creation du provider de ocelot-services.js
		String prefix = "srv_" + RANDOM.nextInt(100_000_000);
		createServicesProvider(prefix, ProviderType.JSON);
		return prefix;
	}

	/**
	 * Create provider of ocelot-services.js and return a part of unic name for ocelot-service.js
	 *
	 * @return
	 */
	void createServicesProvider(String prefix, ProviderType providerType) {
		try (Writer writer = getOpendSourceFileObjectWriter(prefix + ".ServiceProvider")) {
			writer.append("package ").append(prefix).append(";\n");
			writer.append("import org.ocelotds.AbstractServiceProvider;\n");
			writer.append("import org.ocelotds.Constants;\n");
			writer.append("@org.ocelotds.annotations.ServiceProvider(Constants.Provider.").append(providerType.name()).append(")\n");
			writer.append("public class ServiceProvider extends AbstractServiceProvider {\n");
			writer.append("	@Override\n");
			writer.append("	public String getFilename() {\n");
			writer.append("		return \"").append(prefix).append(".").append(providerType.getExtension()).append("\";\n");
			writer.append("	}\n");
			writer.append("}");
		} catch (IOException e) {
			messager.printMessage(Diagnostic.Kind.ERROR, e.getMessage());
		}
	}

	/**
	 * Create writer from filer
	 *
	 * @param name
	 * @return
	 * @throws IOException
	 */
	Writer getOpendSourceFileObjectWriter(String name) throws IOException {
		FileObject source = filer.createSourceFile(name);
		return source.openWriter();
	}

	/**
	 * Create writer from filer
	 *
	 * @param name
	 * @return
	 * @throws IOException
	 */
	Writer getOpendResourceFileObjectWriter(String name, ProviderType providerType) throws IOException {
//			System.out.println(""+resourcejs.toUri().getPath());
//			File file = new File("D:\\Development\\Workspaces\\ocelot-project\\ocelotds.org\\ocelotds.web\\src\\main\\webapp\\test.js");
//			return new FileWriter(file);
		FileObject resource = filer.createResource(StandardLocation.CLASS_OUTPUT, "", name + "." + providerType.getExtension());
		return resource.openWriter();
	}
	
	enum ProviderType {
		JSON("json"), JAVASCRIPT("js");
		final private String ext;
		private ProviderType(String ext) {
			this.ext = ext;
		}
		public String getExtension() {
			return ext;
		}
	}
}
