/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.ocelotds.processors;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import org.ocelotds.annotations.DataService;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Writer;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedOptions;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementVisitor;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import org.ocelotds.Constants;
import org.ocelotds.frameworks.Frameworks;
import org.ocelotds.frameworks.NoFwk;
import org.ocelotds.frameworks.FwkWriter;

/**
 * Processor of annotation org.ocelotds.annotations.DataService
 *
 * @author hhfrancois
 */
@SupportedAnnotationTypes(value = {ProcessorConstants.DATASERVICE_AT})
@SupportedSourceVersion(SourceVersion.RELEASE_7)
@SupportedOptions({ProcessorConstants.DIRECTORY, ProcessorConstants.FRAMEWORK})
public class OcelotProcessor extends AbstractProcessor {

	private static boolean done = false;

	static boolean isDone() {
		return done;
	}

	static void setDone(boolean done) {
		OcelotProcessor.done = done;
	}

	/**
	 * Tools for access filesystem
	 */
	private Filer filer;

	/**
	 * Tools for log processor
	 */
	private Messager messager;

	/**
	 * Directory where save js stub
	 */
	private String jsdir = null;
	
	private ElementVisitor visitorNofwk;
	private ElementVisitor visitorFwk;

	/**
	 * Init processor<br>
	 * get filer, messager<br>
	 * get options
	 *
	 */
	@Override
	public void init(ProcessingEnvironment processingEnv) {
		super.init(processingEnv);
		messager = processingEnv.getMessager();
		filer = processingEnv.getFiler();
		String promiseCreatorScript = getPromiseCreatorScript();
		jsdir = getJsDirectory(processingEnv.getOptions());
		visitorNofwk = getNoFrameworkVisitor(promiseCreatorScript);
		visitorFwk = getJsFrameworkVisitor(getJsFramework(processingEnv.getOptions()), promiseCreatorScript);
	}
	
	/**
	 * Return the default visitor, for no framework 
	 * @param promiseCreatorScript
	 * @return 
	 */
	ElementVisitor getNoFrameworkVisitor(String promiseCreatorScript) {
		return new DataServiceVisitorJsBuilder(processingEnv, promiseCreatorScript, new NoFwk());
	}
	
	/**
	 * Return specific visitor  
	 * @param promiseCreatorScript
	 * @return 
	 */
	ElementVisitor getJsFrameworkVisitor(Frameworks jsfwk, String promiseCreatorScript) {
		return new DataServiceVisitorJsBuilder(processingEnv, promiseCreatorScript, jsfwk.fwkWriter());
	}

	/**
	 * Get optional javascript framework
	 *
	 * @param options
	 * @return
	 */
	Frameworks getJsFramework(Map<String, String> options) {
		if (null != options) {
			if (options.containsKey(ProcessorConstants.FRAMEWORK)) {
				try {
					return Frameworks.valueOf(options.get(ProcessorConstants.FRAMEWORK));
				} catch (NullPointerException | IllegalArgumentException e) {
				}
			}
		}
		return Frameworks.NOFWK;
	}

	/**
	 * Get optional output directory
	 *
	 * @param options
	 * @return
	 */
	String getJsDirectory(Map<String, String> options) {
		if (null != options) {
			if (options.containsKey(ProcessorConstants.DIRECTORY)) {
				return options.get(ProcessorConstants.DIRECTORY);
			}
		}
		return null;
	}

	@Override
	public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
		// check if process was done on previous round
		if (OcelotProcessor.isDone() || roundEnv.processingOver()) { // Returns true if types generated by this round will not be subject to a subsequent round of annotation processing; returns false otherwise.
			return true; //if is it : stop
		}
		for (Element element : roundEnv.getElementsAnnotatedWith(DataService.class)) {
			processElement(element);
		}
		OcelotProcessor.setDone(true);
		return true;
	}
	
	String getPromiseCreatorScript() {
		try (BufferedReader reader = new BufferedReader(new InputStreamReader(OcelotProcessor.class.getResource(ProcessorConstants.PROMISECREATORSCRIPT).openStream()))) {
			return reader.readLine();
		} catch(IOException ioe) {
			
		}
		return "";
	}

	/**
	 * Process element, filter TypeElement only
	 *
	 * @param element
	 */
	public void processElement(Element element) {
		if (TypeElement.class.isInstance(element)) {
			processTypeElement((TypeElement) element);
		}
	}

	/**
	 * Process TypeElement
	 *
	 * @param element
	 */
	public void processTypeElement(TypeElement element) {
		String packagePath = getPackagePath(element);
		String fn = getFilename(element);
		messager.printMessage(Diagnostic.Kind.MANDATORY_WARNING, " javascript generation class : " + element);
		writeJsFileToJsDir(element, visitorFwk, packagePath, fn, jsdir);
		writeJsFile(element, visitorNofwk, packagePath, fn);
	}

	void writeJsFile(TypeElement element, ElementVisitor visitor, String packagePath, String fn) {
		try (Writer w = getResourceFileObjectWriter(packagePath, fn)) {
			element.accept(visitor, w);
		} catch (IOException ioe) {
			messager.printMessage(Diagnostic.Kind.MANDATORY_WARNING, " FAILED TO CREATE : " + packagePath + "." + fn);
		}
	}

	void writeJsFileToJsDir(TypeElement element, ElementVisitor visitor, String packagePath, String fn, String dir) {
		if (null != dir) {
			try (Writer w = getFileObjectWriter(packagePath, fn, dir)) {
				element.accept(visitor, w);
			} catch (IOException ioe) {
				messager.printMessage(Diagnostic.Kind.MANDATORY_WARNING, " FAILED TO CREATE : " + packagePath + "." + fn);
			}
		}
	}

	/**
	 * Get pachage name of class
	 *
	 * @param te
	 * @return
	 */
	String getPackagePath(TypeElement te) {
		return te.getQualifiedName().toString().replaceAll("." + te.getSimpleName(), "");
	}

	/**
	 * Get Js filename from class
	 *
	 * @param te
	 * @return
	 */
	String getFilename(TypeElement te) {
		return te.getSimpleName().toString() + Constants.JS;
	}

	/**
	 * Create writer from filer
	 *
	 * @param name
	 * @return
	 * @throws IOException
	 */
	Writer getSourceFileObjectWriter(String name) throws IOException {
		FileObject source = filer.createSourceFile(name);
		return source.openWriter();
	}

	/**
	 * Create writer from filer
	 *
	 * @param name
	 * @return
	 * @throws IOException
	 */
	Writer getResourceFileObjectWriter(String pkg, String name) throws IOException {
		FileObject resource = filer.createResource(StandardLocation.CLASS_OUTPUT, pkg, name);
		return resource.openWriter();
	}

	/**
	 * Create writer from filer
	 *
	 * @param name
	 * @return
	 * @throws IOException
	 */
	Writer getFileObjectWriter(String pkg, String name, String dirname) throws IOException {
		File dir = new File(dirname);
		if (!dir.exists()) {
			dir.mkdirs();
		}
		return new FileWriter(new File(dir, pkg + "." + name));
	}
}
