/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
 */
package fr.hhdev.ocelot.processors;

import fr.hhdev.ocelot.annotations.DataService;
import java.io.IOException;
import java.io.Writer;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementVisitor;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

/**
 * Processor of annotation fr.hhdev.ocelot.annotations.DataService
 * @author hhfrancois
 */
@SupportedAnnotationTypes(value = {"fr.hhdev.ocelot.annotations.DataService"})
@SupportedSourceVersion(SourceVersion.RELEASE_7)
public class OcelotProcessor extends AbstractProcessor {

	/**
	 * Utilitaire pour accéder au système de fichiers
	 */
	private Filer filer;

	/**
	 * Utilitaire pour afficher des messages lors de la compilation
	 */
	private Messager messager;

	/**
	 * Initialisation de l'Annotation Processor. Permet surtout de récupérer des rÃ©fÃ©rences vers le Filer et le Messager
	 */
	@Override
	public void init(ProcessingEnvironment processingEnv) {
		super.init(processingEnv);
		messager = processingEnv.getMessager();
		filer = processingEnv.getFiler();
	}

	@Override
	public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
		// On verifie si le set d'annotation est vide (elles ont déjà été traitées au round précédent)
		if (roundEnv.processingOver()) {
			return true; // Si c'est le cas on s'arrete la
		}
		// Récupération des packages annotés       
		try {
			FileObject resource = filer.createResource(StandardLocation.CLASS_OUTPUT, "", "ocelot-services.js");
			try (Writer writer = resource.openWriter()) {
				createLicenceComment(writer);
				ElementVisitor visitor = new DataServiceVisitor(processingEnv);
				for (Element element : roundEnv.getElementsAnnotatedWith(DataService.class)) {
					messager.printMessage(Diagnostic.Kind.MANDATORY_WARNING, " JAVASCRIPT GENERATION CLASS : " + element);
					element.accept(visitor, writer);
				}
			}
		} catch (IOException e) {
			messager.printMessage(Diagnostic.Kind.ERROR, e.getMessage());
		}
		return true;
	}

	/* This Source Code Form is subject to the terms of the Mozilla Public
	 * License, v. 2.0. If a copy of the MPL was not distributed with this
	 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
	 */
	/**
	 * Rajoute la licence MPL 2.0
	 * @param writer 
	 */
	protected void createLicenceComment(Writer writer) {
		try {
			writer.append("/* This Source Code Form is subject to the terms of the Mozilla Public\n");
			writer.append(" * License, v. 2.0. If a copy of the MPL was not distributed with this\n");
			writer.append(" * file, You can obtain one at http://mozilla.org/MPL/2.0/.\n");
			writer.append(" * Classes generated by Ocelot Framework.\n");
			writer.append(" */\n");
		} catch(IOException ioe) {}
	}
}
